version: '3.8'
services:
  redis:
    image: redis
    container_name: url-redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: url-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongoexpress:
    image: mongo-express
    container_name: url-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
